import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import theme from '../theme';
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter"; // Import AppRouterCacheProvider
import ClientLayout from "./clientLayout";
// import { PopupProvider } from "@/context/PopUpContext";
// import NavBar from "@/components/NavBar";
// import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Layout component rendered");

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <ClientLayout>
        <AppRouterCacheProvider>
          {/* CssBaseline helps normalize the CSS */}

          {/* <PopupProvider> */}
          {children}
        
          {/* </PopupProvider> */}
        </AppRouterCacheProvider> 
        </ClientLayout>
      </body>
    </html>
  );
}
